# Generated by Django 3.1.2 on 2020-10-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatislove', '0002_auto_20201027_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='img',
        ),
    ]
